backend/accounts/urls.py
from django.urls import path
from . import views

app_name = "accounts"

urlpatterns = [
    # path("signup/", views.signup, name="signup"),
    path("login/", views.user_login,name="login"),
    # path("logout/", views.logout, name="logout"),
    path("profil/", views.user_profil, name="profil"),
    path("profil/<str:username>/", views.user_profil_view, name="profil_view"),
]

backend/blog/urls.py
from django.urls import path

from . import views

app_name = "blog"

urlpatterns = [
    path("", views.home_page, name="home"),
    path("create/", views.create_article, name="create"),
    path("update/<int:article_id>/", views.update_article, name="update"),
    path("delete/<int:article_id>/", views.delete_article, name="delete"),
    path("detail/<int:article_id>/", views.article_page, name="detail"),
]

backend/config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("home.urls")),
    path("accounts/", include("accounts.urls")),
    path("blog/", include("blog.urls")),
    path("ckeditor/", include("ckeditor_uploader.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # import debug_toolbar

    # urlpatterns = [
    #     path("__debug__/", include(debug_toolbar.urls)),
    # ] + urlpatterns
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

backend/home/urls.py
from django.urls import path

from . import views

app_name = "home"

urlpatterns = [
    path("", views.home_page, name="index")
]

backend/accounts/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    pass

backend/blog/models.py
from django.db import models
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Article(models.Model):
    """
    This model represents an article, which consists of a title, content, 
    creation and update timestamps, and a category it belongs to.
    """
    # Model fields
    title = models.CharField(max_length=250, verbose_name="Title")
    # content = models.TextField(verbose_name="Content")
    # content = RichTextField(blank=True, null=True)
    content = RichTextUploadingField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")
    category = models.ForeignKey(Category, on_delete=models.CASCADE, verbose_name="Category")

    slug = models.SlugField(max_length=250, unique=True, verbose_name="Slug", editable=False, default=None)

    def save(self, *args, **kwargs):
        """
        Override the save method to generate a slug based on the article title.
        """
        if not self.slug:
            self.slug = self.title.lower().replace(" ", "-")
        super().save(*args, **kwargs)


    # Model methods
    def __str__(self):
        """
        Returns a string representation of the article object.
        """
        return self.title
    
    def get_absolute_url(self):
        """
        Returns the absolute URL of the article object.
        """
        return f"/blog/{self.id}"
    
    class Meta: # Meta class for Article model.
        ordering = ['-created_at']  # Orders the articles by creation date in descending order


class Comment(models.Model):
    """
    This model represents a comment on an article, which consists of a content,
    creation and update timestamps, and an article it belongs to.
    """
    # Model fields
    content = models.TextField(verbose_name="Content")
    created_at = models.DateTimeField(auto_now_add=True, verbose_name="Created At")
    updated_at = models.DateTimeField(auto_now=True, verbose_name="Updated At")
    article = models.ForeignKey(Article, on_delete=models.CASCADE, verbose_name="Article")

    # Model methods
    def __str__(self):
        """
        Returns a string representation of the comment object.
        """
        return self.content[:100]
    
    class Meta: # Meta class for Comment model.
        ordering = ['-created_at']  # Orders the comments by creation date in descending order

backend/home/models.py
from django.db import models

# Create your models here.

backend/accounts/views.py
from django.shortcuts import redirect, render
from django.conf import settings
from django.contrib.auth import authenticate, login
# Create your views here.

def user_login(request):
    username = request.POST.get('username')
    password = request.POST.get('password')

    if request.method == "POST":
        user = authenticate(
            request, username=username, password=password
        )
        
        if user is not None:
            # Redirect to a success page.
            login(request, user)
            return redirect("home:index")
    return render(request, 'accounts/user_login.html', {})

def user_profil(request):
    user_profil = request.user
    context = {
        'user_profil': user_profil,
    }
    return render(request, 'accounts/user_profil.html', context)

def user_profil_view(request, username):
    User = settings.AUTH_USER_MODEL
    user_profil = User.objects.get(username=username)

    context = {
        'user_profil': user_profil
    }
    return render(request, 'accounts/user_profil.html', context)

backend/blog/views.py
from django.http import HttpResponseNotFound
from django.shortcuts import render
from . models import Article, Category, Comment
from django.db.models import Q

# Create your views here.

def home_page(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''

    articles = Article.objects.filter(
        Q(title__icontains=q) |
        Q(content__icontains=q) |
        Q(category__name__icontains=q)
    )

    categories = Category.objects.all()

    context = {
        'articles': articles,
        'categories': categories,
    }
    return render(request, "blog/index.html", context)

def article_page(request, slug):
    article = Article.objects.get(slug=slug)
    """
    Handles GET and POST requests for article page.
    If GET, renders article page with all comments.
    If POST, creates a new comment and renders article page with all comments.
    """
    if request.method == 'POST':
        comment = request.POST.get('comment')    # Get comment from POST data
        Comment.objects.create(article=article, content=comment)     # Create a new comment
    
    comments = Comment.objects.filter(article=article)  # Get all comments for article

    context = {
        'article': article,
        'comments': comments
    }
    return render(request, "blog/article.html", context)

def create_article(request):
    return render(request, "blog/create.html")

def update_article(request, article_id):
    try:
        article = Article.objects.get(id=article_id)
        return render(request, "blog/update.html", {'article': article})
    except Article.DoesNotExist:
        return HttpResponseNotFound('Article not found.')

def delete_article(request, article_id):
    return render(request, "blog/delete.html")

backend/home/views.py
from django.shortcuts import render

# Create your views here.

def home_page(request):

    context = {
        
    }
    return render(request, "home/index.html", context)

backend/templates/accounts/user_login.html
{% extends "base.html" %}
{% block title %}Connexion{% endblock title %} 
{% block sidebar1 %}{% endblock %} 
{% block sidebar2 %}{% endblock %} 
{% block style %}
<style>

  /* Made with love by Mutiullah Samim*/

  .container {
    height: 100%;
    align-content: center;
  }
  @import url("https://fonts.googleapis.com/css?family=Numans");

  .card {
    height: 370px;
    margin-top: auto;
    margin-bottom: auto;
    width: 400px;
    background-color: rgba(0, 0, 0, 0.5) !important;
  } 
  body {
    background-image: url("http://getwallpapers.com/wallpaper/full/a/5/d/544750.jpg");
    background-size: cover;
    background-repeat: no-repeat;
    height: 100%;
    font-family: "Numans", sans-serif;
  }

  .social-icon {
    position: absolute;
    right: 20px;
    top: -45px;
  }
  .container {
    height: 100%;
    align-content: center;
  }

  .input-group-prepend span {
    width: 50px;
    background-color: #ffc312;
    color: black;
    border: 0 !important;
  }
  .card {
    height: 370px;
    margin-top: auto;
    margin-bottom: auto;
    width: 400px;
    background-color: rgba(0, 0, 0, 0.5) !important;
  }

  input:focus {
    outline: 0 0 0 0 !important;
    box-shadow: 0 0 0 0 !important;
  }
  .social_icon span {
    font-size: 60px;
    margin-left: 10px;
    color: #ffc312;
  }

  .remember {
    color: white;
  }
  .social_icon span:hover {
    color: white;
    cursor: pointer;
  }

  .remember input {
    width: 20px;
    height: 20px;
    margin-left: 15px;
    margin-right: 5px;
  }
  .card-header h3 {
    color: white;
  }

  .login-btn {
    color: black;
    background-color: #ffc312;
    width: 100px;
  }
  .social_icon {
    position: absolute;
    right: 20px;
    top: -45px;
  }

  .login-btn:hover {
    color: black;
    background-color: white;
  }
  .input-group-prepend span {
    width: 50px;
    background-color: #ffc312;
    color: black;
    border: 0 !important;
  }

  .links {
    color: white;
  }
  input:focus {
    outline: 0 0 0 0 !important;
    box-shadow: 0 0 0 0 !important;

    .links a {
      margin-left: 4px;
    }
  }

  .remember {
    color: white;
  }

  .remember input {
    width: 20px;
    height: 20px;
    margin-left: 15px;
    margin-right: 5px;
  }

  .login_btn {
    color: black;
    background-color: #ffc312;
    width: 100px;
  }

  .login_btn:hover {
    color: black;
    background-color: white;
  }

  .links {
    color: white;
  }

  .links a {
    margin-left: 4px;
  }
</style>
{% endblock %}
{% block content %}
{% comment %}
<div class="main-content">
  <h1>Connectez vous</h1>
  <fielset>
    <legende>Entrer vos information</legende>
    <form action="" metho="POST">
      <div class="col-6">
        <label for="email">Email</label>
        <input
          type="email"
          name="email"
          id="email"
          placeholder="example123@mail.com"
        />
      </div>

      <div class="col-6">
        <label for="password">Password</label>
        <input
          type="password"
          name="password"
          id="password"
          placeholder="password123"
        />
      </div>
    </form>
  </fielset>
</div>
{% endcomment %}
	<div class="d-flex justify-content-center h-100">
		<div class="card">
			<div class="card-header">
				<h3>Sign In</h3>
				<div class="d-flex justify-content-end social_icon">
					<span><i class="fab fa-facebook-square"></i></span>
					<span><i class="fab fa-google-plus-square"></i></span>
					<span><i class="fab fa-twitter-square"></i></span>
				</div>
			</div>
			<div class="card-body">
				<form method="POST" action="">
          {% csrf_token %}
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-user"></i></span>
						</div>
						<input type="text" name="username" class="form-control" placeholder="username">
						
					</div>
					<div class="input-group form-group">
						<div class="input-group-prepend">
							<span class="input-group-text"><i class="fas fa-key"></i></span>
						</div>
						<input type="password" class="form-control" name="password" placeholder="password">
					</div>
					<div class="row align-items-center remember">
						<input type="checkbox">Remember Me
					</div>
					<div class="form-group">
						<input type="submit" value="Login" class="btn float-right login_btn">
					</div>
				</form>
			</div>
			<div class="card-footer">
				<div class="d-flex justify-content-center links">
					Don't have an account?<a href="#">Sign Up</a>
				</div>
				<div class="d-flex justify-content-center">
					<a href="#">Forgot your password?</a>
				</div>
			</div>
		</div>
	</div>
    {% endblock content %}
  </div>
</div>

backend/templates/accounts/user_profil.html
{% extends "base.html" %}
{% block title %} {{ user_profil.username|upper }} {% endblock  %} 
{% block sidebar2 %}{% endblock %} 
{% block style %}
<style>
  .gradient-custom {
    /* fallback for old browsers */
    background: #f6d365;

    /* Chrome 10-25, Safari 5.1-6 */
    background: -webkit-linear-gradient(
      to right bottom,
      rgba(246, 211, 101, 1),
      rgba(253, 160, 133, 1)
    );

    /* W3C, IE 10+/ Edge, Firefox 16+, Chrome 26+, Opera 12+, Safari 7+ */
    background: linear-gradient(
      to right bottom,
      rgba(246, 211, 101, 1),
      rgba(253, 160, 133, 1)
    );
  }
</style>
{% endblock %} {% block content %}
<section class="vh-100" style="background-color: #f4f5f7">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col col-lg-6 mb-4 mb-lg-0">
        <div class="card mb-3" style="border-radius: 0.5rem; width: 45em;">
          <div class="row g-0">
            <div
              class="col-md-4 gradient-custom text-center text-white"
              style="
                border-top-left-radius: 0.5rem;
                border-bottom-left-radius: 0.5rem;
              "
            >
              <img
                src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-chat/ava1-bg.webp"
                alt="Avatar"
                class="img-fluid my-5"
                style="width: 80px"
              />
              <h5>{{ user_profil.username }}</h5>
              <p>Web Designer</p>
              <i class="far fa-edit mb-5"></i>
            </div>
            <div class="col-md-8">
              <div class="card-body p-4">
                <h6>Information</h6>
                <hr class="mt-0 mb-4" />
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Email</h6>
                    <p class="text-muted">info@example.com</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Phone</h6>
                    <p class="text-muted">123 456 789</p>
                  </div>
                </div>
                <h6>Projects</h6>
                <hr class="mt-0 mb-4" />
                <div class="row pt-1">
                  <div class="col-6 mb-3">
                    <h6>Recent</h6>
                    <p class="text-muted">Lorem ipsum</p>
                  </div>
                  <div class="col-6 mb-3">
                    <h6>Most Viewed</h6>
                    <p class="text-muted">Dolor sit amet</p>
                  </div>
                </div>
                <div class="d-flex justify-content-start">
                  <a href="#!"><i class="fab fa-facebook-f fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-twitter fa-lg me-3"></i></a>
                  <a href="#!"><i class="fab fa-instagram fa-lg"></i></a>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

backend/templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TECH4ALL-{% block title %}{% endblock title %}</title>
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">
    <!-- Custom CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>

    <!-- Navbar -->
    {% include "base_components/navbar.html" %}

    <!-- Page Content -->
    <div class="container mt-3">
        <div class="row">
            <!-- Sidebar Left -->
             {% block sidebar1 %}
                {% include "base_components/sidebar_left.html" %}
             {% endblock %}
            

            <!-- Main Content -->
            <div class="col-lg-8 col-md-6 main-content">
                {% block content %}
                <h2>Main Content</h2>
                <p>Your content goes here...</p>
                {% endblock  %}
            </div>

            <!-- Sidebar Right -->
            {% block sidebar2 %}
                {% include "base_components/sidebar_right.html" %}
            {% endblock %}

            
        </div>
    </div>

    <!-- Footer -->
    {% include "base_components/footer.html" %}

    <!-- Bootstrap JS with Popper.js -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
    <script src="{% static 'js/base.js' %}"></script>
</body>
</html>

{% block style %}
<style>
</style>
{% endblock %}

backend/templates/base_components/footer.html
<footer class="mt-3">
    <h3>Subscribe to our Newsletter</h3>
    <form>
        <input type="email" placeholder="Enter your email" required>
        <input type="submit" value="Subscribe">
    </form>
    <div class="social-links">
        <a href="#"><i class="fab fa-facebook"></i></a>
        <a href="#"><i class="fab fa-twitter"></i></a>
        <a href="#"><i class="fab fa-instagram"></i></a>
        <a href="#"><i class="fab fa-linkedin"></i></a>
    </div>
</footer>

backend/templates/base_components/navbar.html
<nav class="navbar navbar-expand-lg navbar-custom">
    <div class="container-fluid">
        <!-- Logo -->
        <a class="navbar-brand" href="{% url "home:index" %}">TECH4ALL</a>
        
        <!-- Toggler for smaller screens -->
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon" style="color: white;"><i class="fas fa-bars"></i></span>
        </button>

        <!-- Navbar links -->
        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav ms-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url "home:index" %}"><i class="fas fa-home"></i> Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link popover-tech" href="#" data-bs-toggle="popover" data-bs-content="<a href='#'>Article</a><br><a href='#'>Blog</a><br><a href='#'>News</a>" data-bs-html="true"><i class="fas fa-laptop-code"></i> Tech</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link popover-contact" href="#" data-bs-toggle="popover" data-bs-content="<a href='#'>Contact Us</a><br><a href='#'>About Us</a>" data-bs-html="true"><i class="fas fa-envelope"></i> Contact</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link popover-signup" href="{% url "accounts:profil" %}"  data-bs-html="true"><i class="fas fa-user"></i>{{ user.username }}</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link popover-signup" href="{% url "account:login" %}" data-bs-toggle="popover" data-bs-content="<a href='#'>Sign up</a><br><a href='#'>Sign in</a>" data-bs-html="true"><i class="fas fa-user-plus"></i> Sign up</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <!-- Search -->
                    <form class="d-flex">
                        <input type="text" class="search-bar" placeholder="Search...">
                        <button class="search-bar-btn">Search</button>
                    </form>
                </li>
            </ul>
        </div>
    </div>
</nav>

backend/templates/base_components/sidebar_left.html
<div class="col-lg-2 col-md-3 d-none d-md-block sidebar-left">
    <h2>Services</h2>
    <ul>
        <li><a href="#">Service 1</a></li>
        <li><a href="#">Service 2</a></li>
        <li><a href="#">Service 3</a></li>
    </ul>
</div>

backend/templates/base_components/sidebar_right.html
<div class="col-lg-2 d-none d-lg-block sidebar-right">
    <h2>Recent Activities</h2>
    <ul>
        <li><a href="#">Activity 1</a></li>
        <li><a href="#">Activity 2</a></li>
        <li><a href="#">Activity 3</a></li>
    </ul>
</div>

backend/templates/blog/article.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ article.title }}{% endblock title %}

{% block content %} 
    <div>
        <div>
          {% for article  in articles %}
            <h3> {{article.title}}</h3> <hr>
                {{article.content|safe}}
            
          {% endfor %}
        </div>
    </div>
{% endblock %}

backend/templates/blog/create_article.html
{% extends "base.html" %}
{% load static %}
{% block title %} Add New article {% endblock title %}

{% block content %} 

{% endblock %}

backend/templates/blog/delete_article.html
{% extends "base.html" %}
{% load static %}
{% block title %}delete {{ article.title }}{% endblock title %}

{% block content %} 

{% endblock %}

backend/templates/blog/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}{{ article.title }}{% endblock title %}

{% block content %} 
    {% for article in articles %}
        <h3>{{ article.title }} </h3>
        <div>
            {{ article.content }}
        </div>
    {% endfor %}

{% endblock %}

backend/templates/blog/update_article.html
{% extends "base.html" %}
{% load static %}
{% block title %}update {{ article.title }}{% endblock title %}

{% block content %} 

{% endblock %}

backend/templates/home/index.html
{% extends "base.html" %}
{% load static %}
{% block title %}Acceuil{% endblock title %}

{% block content %} 

{% endblock %}